# SETUP

variables:
  GIT_DEPTH: 5
  CI_IMAGE_DOCKER: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/dd-mobile-bridge:$CURRENT_CI_IMAGE
  CURRENT_CI_IMAGE: 1

stages:
  - ci-image
  - test
  - publish

# CI IMAGE

ci-image:
  stage: ci-image
  when: manual
  except: [tags, schedules]
  tags: ["runner:docker", "size:large"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:18.03.1
  script:
    - docker build --tag $CI_IMAGE_DOCKER -f Dockerfile.gitlab .
    - docker push $CI_IMAGE_DOCKER

# TESTS

test:format:
  tags: [ "runner:main", "size:large" ]
  image: $CI_IMAGE_DOCKER
  stage: test
  timeout: 1h
  script:
    - pip3 install -r requirements/format.txt
    - python3 test_format.py

test:generators:
  tags: [ "runner:main", "size:large" ]
  image: $CI_IMAGE_DOCKER
  stage: test
  timeout: 1h
  script:
    - pip3 install -r requirements/generators.txt
    - python3 test_generators.py

test:readme:
  tags: [ "runner:main", "size:large" ]
  image: $CI_IMAGE_DOCKER
  stage: test
  timeout: 1h
  script:
    - pip3 install -r requirements/readme.txt
    - python3 test_readme.py

# PUBLISH

publish:dd-bridge-android:
  tags: [ "runner:main", "size:large" ]
  only:
    - tags
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - pip3 install -r requirements/dependants.txt
    - aws ssm get-parameter --region us-east-1 --name ci.dd-mobile-bridge.gh_token --with-decryption --query "Parameter.Value" --out text >> ./gh_token
    - git fetch --depth=1 origin master
    - python3 update_dependants.py -s mobile-bridge-api.json -p android -v $CI_COMMIT_TAG

publish:dd-bridge-ios:
  tags: [ "runner:main", "size:large" ]
  only:
    - tags
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - pip3 install -r requirements/dependants.txt
    - aws ssm get-parameter --region us-east-1 --name ci.dd-mobile-bridge.gh_token --with-decryption --query "Parameter.Value" --out text >> ./gh_token
    - git fetch --depth=1 origin master
    - python3 update_dependants.py -s mobile-bridge-api.json -p ios -v $CI_COMMIT_TAG

publish:dd-sdk-reactnative:
  tags: [ "runner:main", "size:large" ]
  only:
    - tags
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - pip3 install -r requirements/dependants.txt
    - aws ssm get-parameter --region us-east-1 --name ci.dd-mobile-bridge.gh_token --with-decryption --query "Parameter.Value" --out text >> ./gh_token
    - git fetch --depth=1 origin master
    - python3 update_dependants.py -s mobile-bridge-api.json -p reactnative -v $CI_COMMIT_TAG